### ISSUE TITLE
can provide all links and full token form how to generate it 

### ISSUE THREAD

**Issue by invisiblecoder99** [allscriptz/jiotv#1]
hello please provide full channel api and how to generate links

**Comment by indiarocks08** [comment]
token generation not working , kindly update

**Comment by ktthesilentkiller** [comment]
i think its fake post

**Comment by indiarocks08** [comment]
hey , pls provide updates

**Comment by invisiblecoder99** [comment]
https://rebrand.ly/blazeintvapkdownload

**Comment by homedecoratie** [comment]
https://rebrand.ly/blazeintvapkdownload

> https://rebrand.ly/blazeintvapkdownload

not working link

**Comment by quickstreamingmedia** [comment]
I have add me Skype quickstreamingmedia I give demo

**Comment by allscriptz** [comment]
Mail to allscripts@protonmail.com for a demo
