### ISSUE TITLE
CORS Errors

### ISSUE THREAD

**Issue by vcfan** [allscriptz/jiotv#3]
There is problem with HTTP Requests.
For example,
1. Error 401 Authorization Required.
https://tv.media.jio.com/streams_live/9XM/9XM_600-1549813728000.key

2. CORS Errors
Access to XMLHttpRequest at 'http://mumsite.cdnsrv.jio.com/jiotv.live.cdn.jio.com/9XM/9XM_600-1549813864000.ts' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by allscriptz** [comment]
The token has to be appended to the url, and if you are playing on the web from http://localhost you will need to proxy the .ts files with a php page or something with the appropriate Access-Control-Allow-Origin: * headers. Mail allscripts@protonmail.com for more info
