### ISSUE TITLE
Generate Token

### ISSUE THREAD

**Issue by vcfan** [allscriptz/jiotv#7]
$jctBase = "cutibeau2ic";

$ssoToken = "AQIC5wM2LY4SfczEZE2fGevb0t17TAm-G9kAMvxhtxL4oGU.*AAJTSQACMDIAAlNLABQtMTkwNjA5MTA1OTI5NDc0NTI1MgACUzEAAjQ4*";

Can anyone plz explain, How to generate such token from original sso token?

**Comment by lakhanadewar** [comment]
https://api.jio.com/v3/users/me

Go to this Url using a Jio Network or Sim Data connection only

**Comment by allscriptz** [comment]
fixed. use the new version
